Repository Team-Peekle/peekle-api-nest, pull requests merged in 2025-08, with the labels that each got.

#5 [Feat] Users 파트 API 초기 구조 세팅
  package-lock.json
  src/app.module.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
Labels: enhancement, D-0

#12 [Feat] Community 모듈 기본 구조 및 API 테스트 코드 작성
  package-lock.json
  src/community/community.controller.spec.ts
  src/community/community.controller.ts
  src/community/community.module.ts
  src/community/community.service.ts
Labels: enhancement, D-1

#13 [Feat] Auth 파트 API 초기 구조 세팅
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
Labels: enhancement, D-0

#25 [Chore] Prisma Article, User 모델 수정
  prisma/schema.prisma
Labels: D-0, 🛠️ Chore

#31 [Feat] 내 정보 조회 및 수정 API 구현
  .gitignore
  prisma/schema.prisma
  src/common/decorators/user-id-decorator.ts
  src/generated/prisma/client.d.ts
  src/generated/prisma/client.js
  src/generated/prisma/default.d.ts
  src/generated/prisma/default.js
  src/generated/prisma/edge.d.ts
  src/generated/prisma/edge.js
  src/generated/prisma/index-browser.js
  src/generated/prisma/index.d.ts
  src/generated/prisma/index.js
  src/generated/prisma/libquery_engine-darwin-arm64.dylib.node
  src/generated/prisma/package.json
  src/generated/prisma/runtime/edge-esm.js
  src/generated/prisma/runtime/edge.js
  src/generated/prisma/runtime/index-browser.d.ts
  src/generated/prisma/runtime/index-browser.js
  src/generated/prisma/runtime/library.d.ts
  src/generated/prisma/runtime/library.js
  src/generated/prisma/runtime/react-native.js
  src/generated/prisma/runtime/wasm-compiler-edge.js
  src/generated/prisma/runtime/wasm-engine-edge.js
  src/generated/prisma/schema.prisma
  src/generated/prisma/wasm.d.ts
  src/generated/prisma/wasm.js
  src/modules/auth/auth.controller.ts
  src/modules/prisma/prisma.service.ts
  src/modules/users/dto/create-user.ts
  src/modules/users/dto/get-me.ts
  src/modules/users/dto/nickname.ts
  src/modules/users/dto/profile.ts
  src/modules/users/dto/terms.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
  tsconfig.json
Labels: D-1

#55 [Feat] 이벤트 상세 조회 API 구현
  src/modules/events/dto/get-event-detail.dto.ts
  src/modules/events/events.controller.ts
  src/modules/events/services/events.query.service.ts
Labels: D-2, ✨ Feature
